(define vacio '())
(define (vacio? x) (if (equal? x vacio) #t #f))
(define (hoja raiz) (list raiz vacio vacio))
(define (hoja? lista) 
    (and (vacio? (cadr lista)) (vacio? (caddr lista)))   
)
(define (izq arbol) (cadr arbol))
(define (der arbol) (caddr arbol))
(define (crear-arbol raiz izq der)
    (cond 
        ((hoja? der) der)
        ((hoja? izq) izq)
        (cos raiz (cons (cons (izq) (der)) '()))
    )
)