(define (separarListas lista elemento)
    (define (mayores lista elemento)
        (cond 
            ((null? lista) '())
            ((>= (car lista) elemento) (cons (car lista) (mayores (cdr lista) elemento)))
            (else (mayores (cdr lista) elemento))
        )
    )
    (define (menores lista elemento)
        (cond 
            ((null? lista) '())
            ((< (car lista) elemento) (cons (car lista) (menores (cdr lista) elemento)))
            (else (menores (cdr lista) elemento))
        )
    )
    (display (mayores lista elemento))
    (newline)
    (display (menores lista elemento))
)